### PR TITLE
Prompt from base class

### PR DESCRIPTION
**Pull request by chapcz**

### CODE REVIEW

**Comment by paveljanda** [comment]
@chapcz Is this method also available in nette/forms 2.3?

**Comment by chapcz** [comment]
yes - also in 2.2 
https://github.com/nette/forms/blob/v2.2.0/src/Forms/Controls/SelectBox.php#L48
https://github.com/nette/forms/blob/v2.3.0/src/Forms/Controls/SelectBox.php#L48

**Comment by paveljanda** [comment]
Thanks.

**Comment by chapcz** [comment]
This commit fixed #2 . 
@paveljanda : Can you release new tag please?

**Pull request merged**
