### PR TITLE
Nette 2.4 support

### PR DESCRIPTION
**Pull request by MartkCz**

### CODE REVIEW

**Comment by MartkCz** [comment]
I wanted to install datagrid with nette 2.4, but composer stoped me at this error.

**Comment by paveljanda** [comment]
And does this package work well with Nette 2.4? A haven't test it yet (And i won't until there is a stable release).

**Comment by MartkCz** [comment]
I've tested it. It works with dev-master.

**Comment by paveljanda** [comment]
Great, thanks.

**Pull request merged**
